steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'lotaya-ai',
        '--source', '.',
        '--region', 'us-west1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
images: []
timeout: '1200s'
